name: Sync Database to Render

on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 3 * * *'  

jobs:
  sync-database:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psycopg2-binary
        
    - name: Start PostgreSQL container
      run: |
        docker-compose up -d db
        sleep 10  # Ждем запуска БД
        
    - name: Create database dump
      run: |
        docker-compose exec -T db pg_dump -U library_user library_db \
          --encoding=UTF8 \
          --format=plain \
          --no-owner \
          --no-privileges \
          --inserts \
          > dump.sql
        
    - name: Split dump into chunks
      run: |
        python scripts/split_dump.py
        
    - name: Sync to Render
      env:
        RENDER_DB_URL: ${{ secrets.RENDER_DATABASE_URL }}
      run: |
        for file in chunk_*.sql; do
          echo "Importing $file..."
          psql "$RENDER_DB_URL" -f "$file"
          if [ $? -eq 0 ]; then
            echo "Success: $file"
          else
            echo "Failed: $file"
            exit 1
          fi
          sleep 2  # Пауза между файлами
        done
        
    - name: Cleanup
      run: |
        rm -f dump.sql chunk_*.sql
        
    - name: Notify success
      if: success()
      run: |
        echo "Database sync completed successfully!"
        
    - name: Notify failure
      if: failure()
      run: |
        echo "Database sync failed!"
        exit 1